#This is the .bashrc of the user in the docker development container

PS1='\[\033[01;32m\]\u@DOCKER_CONT(\h)\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
export CMAKE_EXPORT_COMPILE_COMMANDS=ON

#This is already set in the Dockerfile, but can be overridden here
#export CXX=clang++

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias prepend_path='PATH="$PWD:$PATH"'
